[package]
name = "bklistdbupd01"
version = "0.1.0"
authors = ["jp <jpercyasnet@yahoo.com>"]
edition = "2021"
publish = false

[dependencies]
iced = "^0"
native-dialog = "^0"
iced_futures = "^0"
chrono = "^0"
rusqlite = { version = "^0", features = ["bundled"] }
